        EXTRN VALUE1:BYTE
        EXTRN VALUE2:BYTE
        EXTRN SUM:BYTE
        PUBLIC SUBPROG1
.MODEL SMALL
.CODE
SUBPROG1 PROC FAR
        SUB BX,BX ;INITIALIZE CARRY COUNT
        MOV AL,VALUE1
        MOV AH,VALUE2
        ADD AL,AH ;ADD VALUE1 + VALUE2
        MOV SUM,AL ;STORE SUM
        RET
SUBPROG1 ENDP
END
